"""
Redis Pipeline Template
=======================

Standard template for high-performance, atomic Redis operations using Pipelines.
Generated by the Redis Expert Skill.

Key Features:
- Atomic batch execution (all or nothing)
- Connection handling via redis-py
- Type safety for keys
- Error handling for connection issues

Usage:
1. Inject the `redis_client` dependency.
2. Define your operation within the `execute_pipeline` block.
3. Use strict key naming conventions (e.g., `object:id:field`).
"""

import redis
import logging
from typing import List, Any

logger = logging.getLogger(__name__)


def execute_atomic_updates(
    redis_client: redis.Redis, user_id: str, data: dict, ttl: int = 3600
) -> List[Any]:
    """
    Executes a batch of updates atomically using a Redis Pipeline.

    Args:
        redis_client: The active Redis connection.
        user_id: Unique identifier for the user.
        data: Dictionary of fields to update.
        ttl: Time-to-live in seconds for the keys.

    Returns:
        List of results from the pipeline execution.
    """
    # Define keys
    profile_key = f"user:{user_id}:profile"
    stats_key = f"user:{user_id}:stats"

    pipeline = redis_client.pipeline()

    try:
        # 1. Update Profile Hash (HMSET is deprecated in favor of HSET)
        if data:
            pipeline.hset(profile_key, mapping=data)
            pipeline.expire(profile_key, ttl)

        # 2. Increment generic counter (Example)
        pipeline.incr(stats_key)

        # 3. Execute all commands atomically
        results = pipeline.execute()

        logger.info(f"Successfully updated Redis for user {user_id}")
        return results

    except redis.RedisError as e:
        logger.error(f"Redis pipeline failed for user {user_id}: {str(e)}")
        # Re-raise or handle gracefully depending on requirements
        raise e
